services:
  filter:
    image: mzandtheraspberrypi/imu_websocket_filter:2023-09-03
    stop_signal: SIGINT

  broadcaster:
    image: mzandtheraspberrypi/imu_websocket_broadcaster:2023-09-03
    stop_signal: SIGINT
    devices:
      - "/dev/i2c-3:/dev/i2c-3"
    entrypoint:
      [
        "/entrypoint/read_from_sensor",
        "/dev/i2c-3",
        "0x28",
        "9000"
      ]
