services:
  filter:
    image: mzandtheraspberrypi/imu_websocket_filter:2023-09-17
    stop_signal: SIGINT

  broadcaster:
    image: mzandtheraspberrypi/imu_websocket_broadcaster:2023-09-17
    stop_signal: SIGINT
    devices:
      - "/dev/i2c-3:/dev/i2c-3"
    entrypoint:
      [
        "/entrypoint/read_from_sensor",
        "/dev/i2c-3",
        "0x28",
        "9000"
      ]

  visualizer:
    image: mzandtheraspberrypi/imu_websocket_visualizer:2023-09-17-v2
    stop_signal: SIGINT
    devices:
      - "/dev/i2c-1"
      - "/dev/mem"
    privileged: true
